config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'timesheets#index'

      resources :timesheets, only: [:new, :create]

      resources :weekly_timesheets, only: [:index]
    end
  end

  unauthenticated :user do
    root 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :user

  validates_presence_of :user, :date, :start_time, :finish_time
  validate :can_not_overlap_other_entries
  validate :date_can_not_be_in_the_future
  validate :finish_time_can_not_be_before_start_time
  validate :finish_time_can_not_be_equal_to_start_time

  before_create :set_value

  def friendly_format
    "#{date}: #{start_time.strftime('%H:%M')} - #{finish_time.strftime('%H:%M')} $#{value.round(2)}"
  end

  VALUE_PER_DAY = {
    [1, 3, 5] => [
      [{start_hour: 7, start_minute: 0, finish_hour: 19, finish_minute: 0, value: 22}],
      33
     ],
    [2, 4] => [
      [{start_hour: 5, start_minute: 0, finish_hour: 17, finish_minute: 0, value: 25}],
      35
     ],
    [6, 0] => [
      [],
      47
     ],
  }

  LIMIT = 4
  #

  # 00am - 10am
  # 0am - 5am (Outside the range) ($175)
  # 5am - 10am (Outside) ($175)
  # ($350)

  private

  def set_value
    VALUE_PER_DAY.each do |wday_array, (ranges, outside_value)|
      if wday_array.include?(date.wday)
        duration_in_ranges = 0
        total_value = 0
        ranges.each do |range|
          limit_finish_time = [finish_time, start_time + LIMIT.hours].min
          range_start_time = [start_time, start_time.change(hour: range[:start_hour], min: range[:start_minute])].max
          range_finish_time = [limit_finish_time, finish_time.change(hour: range[:finish_hour], min: range[:finish_minute])].min
          duration_in_range = range_finish_time < range_start_time ? 0 : range_finish_time - range_start_time
          total_value += duration_in_range / 3600.0 * range[:value]
          duration_in_ranges += duration_in_range
        end
        total_value += (finish_time - start_time - duration_in_ranges) / 3600.0 * outside_value
        self.value = total_value
      end
    end
  end

  def date_can_not_be_in_the_future
    errors.add(:date, 'can not be in the future') if date.present? && date > Date.today
  end

  def finish_time_can_not_be_before_start_time
    errors.add(:finish_time, 'can not be before start time') if start_time.present? && finish_time.present? && finish_time < start_time
  end

  def finish_time_can_not_be_equal_to_start_time
    errors.add(:finish_time, 'can not be equal to start time') if start_time.present? && finish_time.present? && finish_time == start_time
  end

  def can_not_overlap_other_entries
    if start_time.present? && finish_time.present?
      if self.class.where("user_id = ? and date = ? and (start_time, finish_time) OVERLAPS (TIME ?, TIME ?)", user_id, date, start_time, finish_time).present?
        errors.add(:base, 'This entry is overlapping another one')
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :timesheets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @timesheets = current_user.timesheets.page(params[:page])
  end

  def new
    @timesheet = Timesheet.new
  end

  def create
    @timesheet = Timesheet.new(timesheet_params.merge(user_id: current_user.id))

    if @timesheet.save
      flash[:success] = 'Timesheet entry created successfully'
      redirect_to root_path
    else
      flash[:danger] = 'The timesheet entry could not be created'
      render 'new'
    end
  end

  private

  def timesheet_params
    params.require(:timesheet).permit(:date, :start_time, :finish_time)
  end

end

app/controllers/weekly_timesheets_controller.rb
class WeeklyTimesheetsController < ApplicationController
  def index
    timesheets = current_user.timesheets.order(:date)
    start_date = timesheets.first.date.beginning_of_week
    end_date = timesheets.last.date.beginning_of_week
    @weekly_summary = {}
    while start_date <= end_date
      this_week_timesheets = timesheets.where(date: start_date..start_date.end_of_week)
      @weekly_summary[start_date] = this_week_timesheets.map{|t| [t.friendly_format]}
      start_date = start_date + 1.week
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/helpers/weekly_timesheets_helper.rb
module WeeklyTimesheetsHelper
end

app/views/layouts/_error_messages.html.slim
- if object.errors.any?
  .message.is-danger
    .message-header The form contains #{pluralize(object.errors.count, 'error')}
    .message-body
      ul
        - object.errors.full_messages.each do |message|
          li = message

app/views/layouts/application.html.slim
doctype html
html
  head
    title Timesheets App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"

  body
    div[style='margin: 1rem']
      - flash.each do |name, message|
        div[class="notification is-#{name == 'alert' ? 'danger' : name == 'notice' ? 'success' : name}"]
          button.delete
          = message
      = yield

app/views/timesheets/index.html.slim
= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'button is-danger is-pulled-right'
=link_to 'Weekly summary', weekly_timesheets_path, class: 'button is-primary is-pulled-right'
= link_to 'Create timesheet entry', new_timesheet_path, class: 'button is-primary is-pulled-right'
h1.title Timesheet entries
.card.card-content
  - if @timesheets.blank?
    p There's no timesheets. Create the first one!
  - else
    = paginate @timesheets
    ul
      - @timesheets.each do |timesheet|
        li = timesheet.friendly_format
    = paginate @timesheets

app/views/timesheets/new.html.slim
= link_to 'Entries', root_path, class: 'button is-pulled-right'
h1.title Create timesheet entry
= render 'layouts/error_messages', object: @timesheet
.card.card-content
  = form_for(@timesheet) do |f|
    .field
      = f.label :date
      .control = f.date_select :date, end_year: Date.today.year
    .field
      = f.label :start_time
      .control = f.time_select :start_time
    .field
      = f.label :finish_time
      .control = f.time_select :finish_time
    .control = f.submit 'Create', class: 'button is-primary'

app/views/weekly_timesheets/index.html.slim
h1.title Weekly Timesheets

table.table
    thead
      tr
        th Week
        th Start date
        th End date
        th Timesheets
    tbody
      - @weekly_summary.each do |date, timesheets|
        tr
          td = date.strftime('%W') 
          td = date
          td = date.end_of_week
          td
            ul
              - timesheets.each do |timesheet|
                li = timesheet